require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RequirementsController do

  def mock_requirement(stubs={})
    @mock_requirement ||= mock_model(Requirement, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all requirements as @requirements" do
      Requirement.stub(:all) { [mock_requirement] }
      get :index
      assigns(:requirements).should eq([mock_requirement])
    end
  end

  describe "GET show" do
    it "assigns the requested requirement as @requirement" do
      Requirement.stub(:find).with("37") { mock_requirement }
      get :show, :id => "37"
      assigns(:requirement).should be(mock_requirement)
    end
  end

  describe "GET new" do
    it "assigns a new requirement as @requirement" do
      Requirement.stub(:new) { mock_requirement }
      get :new
      assigns(:requirement).should be(mock_requirement)
    end
  end

  describe "GET edit" do
    it "assigns the requested requirement as @requirement" do
      Requirement.stub(:find).with("37") { mock_requirement }
      get :edit, :id => "37"
      assigns(:requirement).should be(mock_requirement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created requirement as @requirement" do
        Requirement.stub(:new).with({'these' => 'params'}) { mock_requirement(:save => true) }
        post :create, :requirement => {'these' => 'params'}
        assigns(:requirement).should be(mock_requirement)
      end

      it "redirects to the created requirement" do
        Requirement.stub(:new) { mock_requirement(:save => true) }
        post :create, :requirement => {}
        response.should redirect_to(requirement_url(mock_requirement))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requirement as @requirement" do
        Requirement.stub(:new).with({'these' => 'params'}) { mock_requirement(:save => false) }
        post :create, :requirement => {'these' => 'params'}
        assigns(:requirement).should be(mock_requirement)
      end

      it "re-renders the 'new' template" do
        Requirement.stub(:new) { mock_requirement(:save => false) }
        post :create, :requirement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requirement" do
        Requirement.stub(:find).with("37") { mock_requirement }
        mock_requirement.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :requirement => {'these' => 'params'}
      end

      it "assigns the requested requirement as @requirement" do
        Requirement.stub(:find) { mock_requirement(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:requirement).should be(mock_requirement)
      end

      it "redirects to the requirement" do
        Requirement.stub(:find) { mock_requirement(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(requirement_url(mock_requirement))
      end
    end

    describe "with invalid params" do
      it "assigns the requirement as @requirement" do
        Requirement.stub(:find) { mock_requirement(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:requirement).should be(mock_requirement)
      end

      it "re-renders the 'edit' template" do
        Requirement.stub(:find) { mock_requirement(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requirement" do
      Requirement.stub(:find).with("37") { mock_requirement }
      mock_requirement.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the requirements list" do
      Requirement.stub(:find) { mock_requirement }
      delete :destroy, :id => "1"
      response.should redirect_to(requirements_url)
    end
  end

end
