require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TestCaseEntriesController do

  def mock_test_case_entry(stubs={})
    @mock_test_case_entry ||= mock_model(TestCaseEntry, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all test_case_entries as @test_case_entries" do
      TestCaseEntry.stub(:all) { [mock_test_case_entry] }
      get :index
      assigns(:test_case_entries).should eq([mock_test_case_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested test_case_entry as @test_case_entry" do
      TestCaseEntry.stub(:find).with("37") { mock_test_case_entry }
      get :show, :id => "37"
      assigns(:test_case_entry).should be(mock_test_case_entry)
    end
  end

  describe "GET new" do
    it "assigns a new test_case_entry as @test_case_entry" do
      TestCaseEntry.stub(:new) { mock_test_case_entry }
      get :new
      assigns(:test_case_entry).should be(mock_test_case_entry)
    end
  end

  describe "GET edit" do
    it "assigns the requested test_case_entry as @test_case_entry" do
      TestCaseEntry.stub(:find).with("37") { mock_test_case_entry }
      get :edit, :id => "37"
      assigns(:test_case_entry).should be(mock_test_case_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created test_case_entry as @test_case_entry" do
        TestCaseEntry.stub(:new).with({'these' => 'params'}) { mock_test_case_entry(:save => true) }
        post :create, :test_case_entry => {'these' => 'params'}
        assigns(:test_case_entry).should be(mock_test_case_entry)
      end

      it "redirects to the created test_case_entry" do
        TestCaseEntry.stub(:new) { mock_test_case_entry(:save => true) }
        post :create, :test_case_entry => {}
        response.should redirect_to(test_case_entry_url(mock_test_case_entry))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved test_case_entry as @test_case_entry" do
        TestCaseEntry.stub(:new).with({'these' => 'params'}) { mock_test_case_entry(:save => false) }
        post :create, :test_case_entry => {'these' => 'params'}
        assigns(:test_case_entry).should be(mock_test_case_entry)
      end

      it "re-renders the 'new' template" do
        TestCaseEntry.stub(:new) { mock_test_case_entry(:save => false) }
        post :create, :test_case_entry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested test_case_entry" do
        TestCaseEntry.stub(:find).with("37") { mock_test_case_entry }
        mock_test_case_entry.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :test_case_entry => {'these' => 'params'}
      end

      it "assigns the requested test_case_entry as @test_case_entry" do
        TestCaseEntry.stub(:find) { mock_test_case_entry(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:test_case_entry).should be(mock_test_case_entry)
      end

      it "redirects to the test_case_entry" do
        TestCaseEntry.stub(:find) { mock_test_case_entry(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(test_case_entry_url(mock_test_case_entry))
      end
    end

    describe "with invalid params" do
      it "assigns the test_case_entry as @test_case_entry" do
        TestCaseEntry.stub(:find) { mock_test_case_entry(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:test_case_entry).should be(mock_test_case_entry)
      end

      it "re-renders the 'edit' template" do
        TestCaseEntry.stub(:find) { mock_test_case_entry(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested test_case_entry" do
      TestCaseEntry.stub(:find).with("37") { mock_test_case_entry }
      mock_test_case_entry.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the test_case_entries list" do
      TestCaseEntry.stub(:find) { mock_test_case_entry }
      delete :destroy, :id => "1"
      response.should redirect_to(test_case_entries_url)
    end
  end

end
